module.exports = {
    PROFILE_ACTION: {
        OPEN_AUTH_MODAL: 'OPEN_AUTH_MODAL'
    },
    ATTRIBUTES_CATEGORIES_PRODUCT_ACTION: {
        FETCH_PRODUCT: 'FETCH_PRODUCT',
        FECTH_CATEGORIES: 'FECTH_CATEGORIES',
        FETCH_ATTRIBUTES: 'FETCH_ATTRIBUTES',
        FECTH_DEPARTMENTS: 'FECTH_DEPARTMENTS'
    }
}