module.exports = {
    PROFILE_ACTION: {
        OPEN_AUTH_MODAL: 'OPEN_AUTH_MODAL'
    },
    ATTRIBUTES_CATEGORIES_PRODUCT_ACTION: {
        FETCH_PRODUCT: 'FETCH_PRODUCT',
        FECTH_CATEGORIES: 'FECTH_CATEGORIES',
        FETCH_ATTRIBUTES: 'FETCH_ATTRIBUTES',
        FECTH_DEPARTMENTS: 'FECTH_DEPARTMENTS'
    },
    PRODUCTS: {
        PRODUCTS_LOADING: 'PRODUCTS_LOADING',
        FETCH_PRODUCTS_COMPLETE: 'FETCH_PRODUCTS_COMPLETE',
        POST_PRODUCT_REVIEW: 'POST_PRODUCT_REVIEW'
    }
}