module.exports = {
    PROFILE_ACTION: {
        OPEN_AUTH_MODAL: 'OPEN_AUTH_MODAL',
        TOGGLE_MODAL: 'TOGGLE_MODAL',
        SIGN_IN: 'SIGN_IN',
        SIGN_UP: 'SIGN_UP',
        UPDATE_INFO: 'UPDATE_INFO',
        UPDATE_ADDRESS: 'UPDATE_ADDRESS',
        UPDAE_CC: 'UPDAE_CC',
        FETCH_INFO: 'FETCH_INFO'
    },

    ATTRIBUTES_CATEGORIES_PRODUCT_ACTION: {
        FETCH_PRODUCT: 'FETCH_PRODUCT',
        FECTH_CATEGORIES: 'FECTH_CATEGORIES',
        FETCH_ATTRIBUTES: 'FETCH_ATTRIBUTES',
        FECTH_DEPARTMENTS: 'FECTH_DEPARTMENTS'
    },

    PRODUCTS: {
        PRODUCTS_LOADING: 'PRODUCTS_LOADING',
        PRODUCT_DETAIL_LOADING: 'PRODUCT_DETAIL_LOADING',
        FETCH_PRODUCTS_COMPLETE: 'FETCH_PRODUCTS_COMPLETE',
        FETCH_PRODUCT_DETAILS_COMPLETE: 'FETCH_PRODUCT_DETAILS_COMPLETE',
        POST_PRODUCT_REVIEW: 'POST_PRODUCT_REVIEW',
        CLEAR_SELECTED_PRODUCT: 'CLEAR_SELECTED_PRODUCT'
    },

    SHIPPING: {
        FETCH_SHIPPING_REGION_COMPLETE: 'FETCH_SHIPPING_REGION_COMPLETE',
        FETCH_TAX_DETAILS: 'FETCH_TAX_DETAILS',
        ADD_TO_CART_COMPLETE: 'ADD_TO_CART_COMPLETE',
        DETELTE_CART_ITEM_COMPLETE: 'DETELTE_CART_ITEM_COMPLETE',
        UPDATE_SHOPPING_CART_ID: 'UPDATE_SHOPPING_CART_ID',
        UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
        RESTORE_CART_DETAILS: 'RESTORE_CART_DETAILS',
        GENERATE_CART: 'GENERATE_CART'
    },

    ORDERS: {
        PLACE_ORDER_COMPLETE: 'PLACE_ORDER_COMPLETE',
        PLACE_ORDER_LOADING: 'PLACE_ORDER_LOADING',
        FECTH_ALL_ORDERS: 'FECTH_ALL_ORDERS',
        FETCH_ORDER_CONFIRMATION: 'FETCH_ORDER_CONFIRMATION'
    }

}